apiVersion: v1
kind: Service
metadata:
  name: ${companyname}-${appname}-api
  labels:
    run: ${companyname}-${appname}-api
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    name: http
  selector:
    run: ${companyname}-${appname}-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${companyname}-${appname}-api
spec:
  replicas: ${DEPLOY_VARS_replicas}
  selector:
    matchLabels:
      run: ${companyname}-${appname}-api
  template:
    metadata:
      labels:
        run: ${companyname}-${appname}-api
    spec:
      containers:
      - name: ${companyname}-${appname}-api
        image: ${CONTAINER_IMAGE}
        env:
        - name: ENVIRONMENT_NAME
          value: ${ENVIRONMENT_NAME}
        ports:
        - containerPort: 3000